### ISSUE TITLE
Latest VSCode v1.50 breaks `Enable monkey patch` command?

### ISSUE THREAD

**Issue by JodyStats** [iocave/monkey-patch#17]
Hello, thank you for creating this extension and I have been using this for half a year. I use this extension together with `iocave/customize-ui`

Had no issues at all until just now where I literally upgraded VSCode to v1.50, `Enable monkey patch` command (as usual every time I updated VSCode).

VSCode v1.50
Monkey patch v0.1.10
Customize UI v0.1.46

After `Enable monkey patch`, I restart VSCode. VSCode did not launch at all. Go to command line `code --version` and I got this

```powershell
PS C:\Users\jody> code --version
C:\Program Files\Microsoft VS Code\resources\app\out\bootstrap.js:7
if(!o||!n)return void console.warn("setupNLS() is only available in node.js environments");let e={availableLanguages:{}};if(process.env.VSCODE_NLS_CONFIG)try{e=JSON.parse(process.env.VSCODE_NLS_CONFIG)}catch(e){}if(e._resolvedLanguagePackCoreLocation){const r=Object.create(null);e.loadBundle=function(t,i,s){const a=r[t];if(a)return void s(void 0,a);const c=o.join(e._resolvedLanguagePackCoreLocation,`${t.replace(/\//g,"!")}.nls.json`);n.promises.readFile(c,"utf8").then((function(e){const o=JSON.parse(e);r[t]=o,s(void 0,o)})).catch(o=>{try{e._corruptedFile&&n.promises.writeFile(e._corruptedFile,"corrupted","utf8").catch((function(e){console.error(e)}))}finally{s(o,void 0)}})}}return e},fileUriFromPath:function(e,o){let n,r=e.replace(/\\/g,"/");return r.length>0&&"/"!==r.charAt(0)&&(r=`/${r}`),(n=o.isWindows&&r.startsWith("//")?encodeURI(`${o.scheme||"file"}:${r}`):encodeURI(`${o.scheme||"file"}://${o.fallbackAuthority||""}${r}`)).replace(/#/g

TypeError: Cannot read property 'isWindows' of undefined
    at Object.fileUriFromPath (C:\Program Files\Microsoft VS Code\resources\app\out\bootstrap.js:7:808)
    at Object.<anonymous> (C:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-amd.js:17:49)
    at Module._compile (internal/modules/cjs/loader.js:1014:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1051:10)
    at Module.load (internal/modules/cjs/loader.js:862:32)
    at Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:899:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Program Files\Microsoft VS Code\resources\app\out\cli.js:5:199)
    at Module._compile (internal/modules/cjs/loader.js:1014:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1051:10)
    at Module.load (internal/modules/cjs/loader.js:862:32)
    at Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1103:10)
    at internal/main/run_main_module.js:17:11
``` 

Things I have tried. Reinstall VSCode, it can be launched again, then `Enable monkey patch` again, then same things happen. I tried this for 3 times without any luck. What is the issue here?

Thank you for the help.

**Comment by knopp** [comment]
Latest monkey patch version is 0.1.11, is there any reason why you're still on 0.1.10?

**Comment by JodyStats** [comment]
Installed 0.1.11 and it solves the issue. Closing this. Thank you
