### ISSUE TITLE
Monkey path not loading in VSCode 1.74.0

### ISSUE THREAD

**Issue by golimpio** [iocave/monkey-patch#55]
VSCode won't start.  I'm testing it on macOS 13.0.1

```
❯ code --version
1.74.0
5235c6bb189b60b01b1f49062f4ffa42384f8c91
x64
```

```
❯ code --verbose
Loading monkey-patch
(node:56390) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'crypto')
    at P (/Applications/Dev/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:25:24056)
    at i (/Applications/Dev/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:25:33504)
    at get mainIPCHandle (/Applications/Dev/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:32:6945)
    at p.<computed> (/Applications/Dev/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:3:53298)
    at Oe.c (/Applications/Dev/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:84:7310)
    at Oe.b (/Applications/Dev/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:84:5809)
    at Oe.a (/Applications/Dev/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:84:4864)
    at Oe.main (/Applications/Dev/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:84:4709)
    at Object.<anonymous> (/Applications/Dev/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:85:1732)
    at s._safeInvokeFunction (/Applications/Dev/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:1337)
    at s._invokeFactory (/Applications/Dev/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:1522)
    at s.complete (/Applications/Dev/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:1801)
    at s._onModuleComplete (/Applications/Dev/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:6:1112)
    at s._onModuleComplete (/Applications/Dev/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:6:1358)
    at s._resolve (/Applications/Dev/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:6:510)
    at s.defineModule (/Applications/Dev/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:6066)
    at n (/Applications/Dev/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:10527)
    at Object.R (/Applications/Dev/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:6:6036)
    at s._safeInvokeFunction (/Applications/Dev/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:1337)
    at s._invokeFactory (/Applications/Dev/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:1522)
    at s.complete (/Applications/Dev/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:1801)
    at s._onModuleComplete (/Applications/Dev/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:6:1112)
    at s._onModuleComplete (/Applications/Dev/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:6:1358)
    at s._resolve (/Applications/Dev/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:6:510)
    at s.defineModule (/Applications/Dev/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:6066)
    at y (/Applications/Dev/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:6:1825)
    at h (/Applications/Dev/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:2554)
    at Object.<anonymous> (/Applications/Dev/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.nls.js:3:61)
    at e._createAndEvalScript (/Applications/Dev/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:2598)
    at /Applications/Dev/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:2237
    at /Applications/Dev/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js:82:14
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
(Use `Electron --trace-warnings ...` to show where the warning was created)
(node:56390) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**Comment by sstativa** [comment]
Same error, but on Apple Silicon.

**Comment by JackEllis** [comment]
+1 also having issues. I apply monkey patch and then VS Code won't open after a restart. This is a monkey patch to hide the top bar.

Solution for now is to re-install the Mac app (download & overwrite .app file) and just not run the monkey patch.

**Comment by NetanelH2** [comment]
It happens to me as well in macOS.
The only solution I found so far is to go back to vscode version 1.73

**Comment by vipulrawat** [comment]
https://github.com/iocave/customize-ui/issues/156

**Comment by tuxmanu** [comment]
Same here, not able to start VSC after updating to 1.74.0 and re-applying monkeypatch. on MacOs 12.6.1

**Comment by owencyr** [comment]
long story short there was a breaking change in 1.74. you either downgrade to 1,73, or disable monkeypatch + customize UI

**Comment by lethefrost** [comment]
Same here, waiting for an update. Is it forever broken or does there exist any workaround? Thank you so much for this awesome extension ❤️

**Comment by johnnyshankman** [comment]
Ran into this today. Glad this thread was here to make me not feel insane 👍  a fix would be awesome

**Comment by OneTuskedMario** [comment]
Looking at the customize ui thread started by the author it seems it is forever going to be broken because vscode changed a fundamental mechanic on how their typescript private fields are accessed. The only workaround for now is downgrading as far as I know

**Comment by sstativa** [comment]
In theory, if the Monkey patch was used only for CustomizeUI and a simple CSS customization, some of these customisations might be reproduced directly in `Contents/Resources/app/out/vs/workbench/workbench.desktop.main.css`. 
Of course, VSCode will throw a warning on start but at least it can be suppressed and won't bother you till next update of VSCode.

**Comment by Xelbayria** [comment]
I have the same problem where I re-apply MonkeyPatch and then restart VSC. It doesn't open at all after restarting. 
my OS is: Windows 10 pro, 64bit

**Comment by solc42** [comment]
Is it possible to disable plugin(in my case Customize UI) via config files, to start the app?

Found https://github.com/microsoft/vscode/issues/40239 but tbh did not get the final idea about where and how to do it O.o

Tried a guess and removed _iocave*_ records from **$HOME/.vscode/extensions/extensions.json** and also delete the _iocave*_ directories - nothing changed, still start fails with same error.

**Comment by PleahMaCaka** [comment]
😭

**Comment by dwhenson** [comment]
😢

**Comment by kud** [comment]
> +1 also having issues. I apply monkey patch and then VS Code won't open after a restart. This is a monkey patch to hide the top bar.
> 
> Solution for now is to re-install the Mac app (download & overwrite .app file) and just not run the monkey patch.

I confirm.

**Comment by ryanberckmans** [comment]
If vsc 1.74+ is now incompatible with monkey-patch, has vsc added a way to hide the UI's top bar without monkey-patch? Hiding the top bar is important for vertical space maximization. Being able to upgrade to 1.74+ is important, too. We can't stay on 1.73 forever, and it sounds like some of us have been working with the top bar hidden for years. What's up?

**Comment by esonec** [comment]
I use monkey patch to customize fonts and font sizes for VSCode Explorer, Outline, Terminal.
And also for other customization features. I will have to stay with 1.73 unless Monkey patch will be re-enabled in future versions of VSCode. I encourage MS to re-enable Monkey patch.

**Comment by trvswgnr** [comment]
I doubt Microsoft will update the official VSCode to fix the breaking changes from https://github.com/microsoft/vscode/pull/166126.

The good news is [VSCodium](https://github.com/VSCodium/vscodium/tree/insider) has removed the mangling to specifically resolve issues like these. Now Monkey Patch just needs to do some upkeep and support it.

See https://github.com/VSCodium/vscodium/issues/1390#issuecomment-1407788309.
