### ISSUE TITLE
After enabling monkey patch my vscode is not visible anymore on MacOs

### ISSUE THREAD

**Issue by felixele217** [iocave/monkey-patch#56]
These are my CustomizeUI Settings

<img width="296" alt="image" src="https://user-images.githubusercontent.com/50794814/206524962-abd416ad-ed2a-4676-84cf-7fbfe90eaa46.png">

I have MonkeyPatch and CustomizeUI enabled and after enabling Monkey Patch, my VSCode is not visible anymore after opening.

<img width="380" alt="image" src="https://user-images.githubusercontent.com/50794814/206525267-acb8fcc7-a96d-42aa-b746-eaa6c7a207be.png">

Anyone else having this issue?

**Comment by Sinderella** [comment]
Probably https://github.com/iocave/customize-ui/issues/156

**Comment by Frank-Mayer** [comment]
Same Problem here 🙋‍♂️

**Comment by zsy619** [comment]
Same Problem here 🙋‍♂️
12.6.2 (21G320)

vscode Version: 1.74.0 (Universal)

**Comment by b-lov** [comment]
same problem on M1 MacBook Air. I uninstalled customize-ui and monkey-patch extensions via commandline with `code --uninstall-extension ...` and got a success message, I also deleted both extension folders from `~/.vscode/extensions`. Still when I try to launch vscode it remains invisible. When launching it with the `--verbose` tag it still says 'Loading monkey-patch'. Launching with `--disable-extensions` also doesn't work. Does anyone have an idea how to prevent it from trying to load monkey patch and get it to start without completely reinstalling?

**Comment by knopp** [comment]
You need to re-install vscode at this point. Just the app bundle, your settings, extension etc will remain untouched.

**Comment by G33kNoob** [comment]
same issue

**Comment by binaryben** [comment]
Same issue here on Codium running Ventura

**Comment by GJRobert** [comment]
> You need to re-install vscode at this point. Just the app bundle, your settings, extension etc will remain untouched.

Which version of VS Code to re-install, please?

**Comment by b-lov** [comment]
if you want to use monkey patch, 1.73. If you want the newest version without monkey patch, just reinstall the newest version and disable monkey patch. if you have homebrew, you can just go `brew reinstall --cask visual-studio code` and disable monkey patch on next startup. if you want an earlier version, you have to download it manually.

**Comment by forivall** [comment]
Hey, I have a basic fix submitted as a PR at #58 so that it shouldn't hose your vscode install anymore.

**Comment by pm0u** [comment]
@b-lov I get no cask exists with name 'code' when I try to run that.

The recommended formulae appears to be: `brew install --cask visual-studio-code`

https://formulae.brew.sh/cask/visual-studio-code#default

**Comment by b-lov** [comment]
> @b-lov I get no cask exists with name 'code' when I try to run that.
> 
> The recommended formulae appears to be: `brew install --cask visual-studio-code`
> 
> https://formulae.brew.sh/cask/visual-studio-code#default

sorry, you're right. i fixed the typo. you can use `reinstall` instead of `install` if you had it installed before and it stopped working after the update.

**Comment by danilinus** [comment]
Same here, I'm using Mac OS Monterey 12.6

**Comment by julienaub** [comment]
Same here. I had to uninstall VSCode and reinstall it so that Monkey Patch gets disabled.

**Comment by IJuanI** [comment]
Same here with Mac OS Monterey 12.3

**Comment by pm0u** [comment]
any progress on this? I have vscode locked to 1.73 but some extensions are now requiring 1.74 so I'd love to be able to update vscode and use all my preferred extensions.

**Comment by pm0u** [comment]
I just re-enabled auto updates since this was marked resolved, updated to 1.74 and my vscode broke again, I don't believe this is resolved --

```
Loading monkey-patch
(node:51000) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'crypto')
    at P (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:25:24056)
    at i (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:25:33504)
    at get mainIPCHandle (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:32:6945)
    at p.<computed> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:3:53298)
    at Oe.c (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:84:7310)
    at Oe.b (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:84:5809)
    at Oe.a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:84:4864)
    at Oe.main (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:84:4709)
    at Object.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:85:1732)
    at s._safeInvokeFunction (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:1337)
    at s._invokeFactory (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:1522)
    at s.complete (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:1801)
    at s._onModuleComplete (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:6:1112)
    at s._onModuleComplete (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:6:1358)
    at s._resolve (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:6:510)
    at s.defineModule (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:6066)
    at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:10527)
    at Object.R (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:6:6036)
    at s._safeInvokeFunction (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:1337)
    at s._invokeFactory (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:1522)
    at s.complete (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:1801)
    at s._onModuleComplete (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:6:1112)
    at s._onModuleComplete (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:6:1358)
    at s._resolve (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:6:510)
    at s.defineModule (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:6066)
    at y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:6:1825)
    at h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:2554)
    at Object.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.nls.js:3:61)
    at e._createAndEvalScript (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:2598)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:2237
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js:82:14
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
(Use `Electron --trace-warnings ...` to show where the warning was created)
(node:51000) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**Comment by The-Compiler** [comment]
@pm0u Issues in development repos are typically closed when a fix is merged into the master/main branch - that [happened](https://github.com/iocave/monkey-patch/commit/065d2ea88d76ec5110103058631bcdfe620161cb) a week ago, but the [last release](https://marketplace.visualstudio.com/items?itemName=iocave.monkey-patch) is from October. So unless you're packaging/running the extension from the git repository, you won't have the change yet.

**Comment by pm0u** [comment]
@The-Compiler thanks for the clarification. I didn't see any releases on this repo so I assumed the extension just tracked master.

**Comment by binaryben** [comment]
Does the upcoming fix mean Customize UI will work again?

**Comment by The-Compiler** [comment]
@binaryben no, see the PR description in #58

**Comment by GJRobert** [comment]
> I've been using monkey-patch for months and suddenly today I'm now running into this issue. Why was it not a problem until now?

@electrovir perhaps you have not updated your VS Code for long until today.

It has to do with VS Code upstream, not problem of Monkey Patch / Custom UI.

**Comment by hugobiais** [comment]
For those of you who have to reinstall VS Code like I did, I would suggest making a copy of your `settings.json` file before uninstalling the broken version. The file can be found at `~/Library/Application\ Support/Code/User/settings.json`. Then, once you have reinstalled VS Code, just copy your old settings.json into the new one (You might not have to if you had Sync Settings already on).

**Comment by saepien** [comment]
Same thing just happened to me. Had to download/reinstall VSCode and removed both Customize Ui and Patch Monkey. Any update on a fix? Would be nice to not squint to read (sidebar) debugger panels.

**Comment by GJRobert** [comment]
@saepien you can read the whole thread, there is a fix no need to reinstall VSCode but I never tried anyway because I reinstalled in the first days. And seems to fix for Monkey Patch to work in 1.74+.

**Comment by tourervit** [comment]
- (optional) Copy everything from /Users/:user/Library/Application Support/Code/User
- Download 1.73 https://code.visualstudio.com/updates/v1_73
- Move it to the Applications folder (Keep Both)
- Move Visual Studio to Trash
- Rename Visual Studio Code 2 to Visual Studio Code

**Comment by GJRobert** [comment]
I have switched to VSCodium 1.74+ (now I'm using VSCodium 1.76.1), where a modified version of MonkeyPatch works (with Custom UI!). ☞ https://github.com/VSCodium/vscodium/issues/1390#issuecomment-1411187403
I have migrated most of my VS Code profile settings to VSCodium with ease. (tell me to post an English version of migration if needed)

MonkeyPatch + CustomUI is essential! Please keep it guys~

**Comment by t1noo7** [comment]
> You need to re-install vscode at this point. Just the app bundle, your settings, extension etc will remain untouched.

thank u so much much! U actually save my life!!!
Kiss U never stop bro!
